name: wheelz
description: This is Flutter Uber Clone - Users App.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus:
  firebase_core: ^2.24.2
  firebase_auth:
  firebase_database:
  get: ^4.6.6
  geolocator: ^10.1.0
  image_picker: ^1.0.6
  firebase_storage: ^11.5.6
  provider: ^6.1.1
  # flutter_map: ^6.1.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  dio: ^5.4.0
  permission_handler: ^11.1.0
  # flutter_map_location_marker: ^8.0.3
  flutter_polyline_points: ^2.0.0
  flutter_map_directions: 0.0.4
  flutter_map_location_marker: ^7.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - themes/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

